---
title: "Untitled"
output: html_document
date: '2023-03-02'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(teamcolors)
library(directlabels)
library(ggrepel)
library(lme4)
library(broom)
library(purrr)
library(sjPlot)
library(cowplot)
library(modelr)
library(mgcv) #gam
library(randomForest)
library(sportyR)
library(ggdark)
library(scales)
library(svglite)
library(parallel)
library(doParallel)
library(foreach)
library(MASS)
#remotes::install_github("marcpaterno/rcosmosis")
library(rcosmosis)
library(wCorr)
source("lib/court.R")
source("lib/viztools.R")
options(future.globals.maxSize= 8912896000)
play_by_play_with_free_throw_results_shots <- read_csv("data/play_by_play_with_free_throw_results_shots_simulated_missed_fouled.csv")

```


```{r}
n.cores <- parallel::detectCores() - 1
n.cores <- 48
my.cluster <- parallel::makeCluster(
  n.cores, 
  type = "PSOCK"
  )

#check cluster definition (optional)
print(my.cluster)

#register it to be used by %dopar%
doParallel::registerDoParallel(cl = my.cluster)

#check if it is registered (optional)
foreach::getDoParRegistered()
foreach::getDoParWorkers()
```



```{r}
play_by_play_with_free_throw_results_shots  %>% filter(playoffs == F) ->  play_by_play_with_free_throw_results_reg_season
play_by_play_with_free_throw_results_reg_season %>% filter(!is.na(x), !is.na(y), !is.na(true_points)) -> play_by_play_with_free_throw_results_reg_season_attempts

play_by_play_with_free_throw_results_reg_season_attempts %>% pull(true_points) %>% mean() -> average_true_shot_value


shot_position_model_gam = gam(true_points ~ s(x,y) ,data=play_by_play_with_free_throw_results_reg_season_attempts, weights = simulated_fouled_missed_fouled_shots_weight)
# shot_position_model_loess = loess(true_points ~ x+y,data=play_by_play_with_free_throw_results_reg_season_attempts)
# shot_position_model_rf = randomForest(true_points ~ x+y,data=play_by_play_with_free_throw_results_reg_season_attempts)

grid_dim <- 200
#grid_tile_width <- (max(play_by_play_with_free_throw_results_reg_season_attempts$x)-min(play_by_play_with_free_throw_results_reg_season_attempts$x))/grid_dim
#grid_tile_height <- (max(play_by_play_with_free_throw_results_reg_season_attempts$y)-min(play_by_play_with_free_throw_results_reg_season_attempts$y))/grid_dim
grid_tile_width <- 50/grid_dim
grid_tile_height <- 50/grid_dim#this will make it uniform(94/2)/grid_dim

#play_by_play_with_free_throw_results_reg_season_attempts %>% data_grid(x = seq_range(x, n=grid_dim), y = seq_range(y, n=grid_dim)) -> grid
play_by_play_with_free_throw_results_reg_season_attempts %>% data_grid(x = seq(0,50,grid_tile_width), y = seq(0,(94/2),grid_tile_height)) -> grid



grid$true_points <- predict(shot_position_model_gam, grid)
grid %>% filter(true_points >= 0) -> grid
#grid %>% ggplot(aes(x=x, y=y)) + geom_tile(aes(fill=true_points)) + geom_point(data = grid %>% slice(which.max(true_points))) + geom_contour(aes(z=true_points)) + scale_fill_gradient2(low="blue", mid="white", high = "red", midpoint = 1) + theme_bw()
#plot(shot_position_model_gam, page = 1, scheme = 2) 

grid %>% pull(true_points) %>% min() -> min_true_shot_value
grid %>% pull(true_points) %>% max() -> max_true_shot_value

#P_half_180 + geom_point(data = play_by_play_with_free_throw_results_reg_season_attempts %>% sample_n(10000), aes(color=`3PT`,x=x, y=y))
#P_half_180 + geom_tile(data = grid, aes(fill=true_points,x=x, y=y), alpha=0) + geom_point(data = grid %>% slice(which.max(true_points)), aes(fill=true_points,x=x, y=y)) + geom_contour(data = grid, aes(z=true_points,x=x, y=y)) + scale_fill_gradient2(low="blue", mid="white", high = "red", midpoint = 1) + theme_bw()

#play_by_play_with_free_throw_results_reg_season_attempts %>% ggplot(aes(x=x, y=y)) + geom_hex() + geom_polygon(data = rotate_court(court[court$side==1,], theta = 0), aes(x = x, y = y, group = group), col = "gray")

grid %>% ggplot(aes(x=x, y=y)) + geom_tile(aes(fill=true_points), width=grid_tile_width, height=grid_tile_height) + geom_point(data = grid %>% slice(which.max(true_points))) + geom_contour(aes(z=true_points)) + scale_fill_gradientn(colors = c("blue", "black", "red"), na.value = "green", values = rescale(c(min_true_shot_value, average_true_shot_value, max_true_shot_value))) + theme_bw() + geom_polygon(data = rotate_court(court[court$side==1,], theta = 0), aes(x = x, y = y, group = group), col = "gray") +
  coord_fixed(ratio = 1) +
  xlim(-2,50) +
  ylim(-55,2) +
  scale_x_continuous(breaks = c(0, 25,  50)) +
  scale_y_continuous(breaks = c(0, 23.5, 47)) +
  xlab("") + ylab("") + ggtitle("GAM Model") + dark_theme_gray() -> league_plot

saveImage(league_plot, filename = "visuals/shot_charts.png")
```


```{r}
create_gam_shot_chart <- function(data, value, title, subtitle, fill_title,min_true_shot_value, average_true_shot_value, max_true_shot_value){
  value = ensym(value)
  custom_caption <- paste0("*Midpoint of palette is league average of ", round(average_true_shot_value,2), ".")
  if(average_true_shot_value == 0){
    custom_caption <- paste0("*Midpoint of palette is ", round(average_true_shot_value,2), ".")
  }
  data %>% ggplot(aes(x=x, y=y)) + geom_tile(aes(fill=!!value), width=grid_tile_width, height=grid_tile_height) + geom_point(data = grid %>% slice(which.max(!!value))) + geom_contour(aes(z=!!value)) + scale_fill_gradientn(colors = c("blue", "black", "red"), na.value = "green", values = rescale(c(min_true_shot_value, average_true_shot_value, max_true_shot_value))) + theme_bw() + geom_polygon(data = rotate_court(court[court$side==1,], theta = 0), aes(x = x, y = y, group = group), col = "gray") +
  coord_fixed(ratio = 1) +
  xlim(-2,50) +
  ylim(-55,2) +
  scale_x_continuous(breaks = c(0, 25,  50)) +
  scale_y_continuous(breaks = c(0, 23.5, 47)) +
  xlab("") + ylab("") + labs(caption = custom_caption,title = title, subtitle = subtitle, fill=fill_title) + dark_theme_dark() -> shot_chart
  return(shot_chart)
}
  create_gam_shot_chart_two_color <- function(data, value, title, subtitle, fill_title){
    value = ensym(value)
   
    data %>% ggplot(aes(x=x, y=y)) + geom_tile(aes(fill=!!value), width=grid_tile_width, height=grid_tile_height) + geom_point(data = grid %>% slice(which.max(!!value))) + geom_contour(aes(z=!!value)) + scale_fill_gradient(low = "black", high="red") + theme_bw() + geom_polygon(data = rotate_court(court[court$side==1,], theta = 0), aes(x = x, y = y, group = group), col = "gray") +
    coord_fixed(ratio = 1) +
    xlim(-2,50) +
    ylim(-55,2) +
    scale_x_continuous(breaks = c(0, 25,  50)) +
    scale_y_continuous(breaks = c(0, 23.5, 47)) +
    xlab("") + ylab("") + labs(title = title, subtitle = subtitle, fill=fill_title) + dark_theme_dark() -> shot_chart
    return(shot_chart)
  }
```

```{r}
clusterCall(my.cluster, function() {
  library(tidyverse)
  library(teamcolors)
  library(directlabels)
  library(ggrepel)
  library(lme4)
  library(broom)
  library(purrr)
  library(sjPlot)
  library(cowplot)
  library(modelr)
  library(mgcv) #gam
  library(randomForest)
  library(sportyR)
  library(ggdark)
  library(scales)
  library(svglite)
  library(parallel)
  library(doParallel)
  library(foreach)
  library(MASS)
  library(rcosmosis)
  library(wCorr)
  source("lib/court.R")
  source("lib/viztools.R")
  create_gam_shot_chart <- function(data, value, title, subtitle, fill_title,min_true_shot_value, average_true_shot_value, max_true_shot_value){
    value = ensym(value)
    custom_caption <- paste0("*Midpoint of palette is league average of ", round(average_true_shot_value,2), ".")
    if(average_true_shot_value == 0){
      custom_caption <- paste0("*Midpoint of palette is ", round(average_true_shot_value,2), ".")
    }
    data %>% ggplot(aes(x=x, y=y)) + geom_tile(aes(fill=!!value), width=grid_tile_width, height=grid_tile_height) + geom_point(data = grid %>% slice(which.max(!!value))) + geom_contour(aes(z=!!value)) + scale_fill_gradientn(colors = c("blue", "black", "red"), na.value = "green", values = rescale(c(min_true_shot_value, average_true_shot_value, max_true_shot_value))) + theme_bw() + geom_polygon(data = rotate_court(court[court$side==1,], theta = 0), aes(x = x, y = y, group = group), col = "gray") +
    coord_fixed(ratio = 1) +
    xlim(-2,50) +
    ylim(-55,2) +
    scale_x_continuous(breaks = c(0, 25,  50)) +
    scale_y_continuous(breaks = c(0, 23.5, 47)) +
    xlab("") + ylab("") + labs(caption = custom_caption,title = title, subtitle = subtitle, fill=fill_title) + dark_theme_dark() -> shot_chart
    return(shot_chart)
  }
  
  
   create_gam_shot_chart_two_color <- function(data, value, title, subtitle, fill_title){
    value = ensym(value)
   
    data %>% ggplot(aes(x=x, y=y)) + geom_tile(aes(fill=!!value), width=grid_tile_width, height=grid_tile_height) + geom_point(data = grid %>% slice(which.max(!!value))) + geom_contour(aes(z=!!value)) + scale_fill_gradient(low = "black", high="red") + theme_bw() + geom_polygon(data = rotate_court(court[court$side==1,], theta = 0), aes(x = x, y = y, group = group), col = "gray") +
    coord_fixed(ratio = 1) +
    xlim(-2,50) +
    ylim(-55,2) +
    scale_x_continuous(breaks = c(0, 25,  50)) +
    scale_y_continuous(breaks = c(0, 23.5, 47)) +
    xlab("") + ylab("") + labs(title = title, subtitle = subtitle, fill=fill_title) + dark_theme_dark() -> shot_chart
    return(shot_chart)
  }
  print("finished")
  
})


```


```{r}

play_by_play_with_free_throw_results_shots  %>% filter(playoffs == F) ->  play_by_play_with_free_throw_results_reg_season
play_by_play_with_free_throw_results_reg_season %>% filter(!is.na(x), !is.na(y), !is.na(true_points)) -> play_by_play_with_free_throw_results_reg_season_attempts
play_by_play_with_free_throw_results_reg_season_attempts %>% pull(true_points) %>% mean() -> average_true_shot_value
shot_position_model_gam = gam(true_points ~ s(x,y) ,data=play_by_play_with_free_throw_results_reg_season_attempts, weights = simulated_fouled_missed_fouled_shots_weight)
grid_dim <- 200
grid_tile_width <- 50/grid_dim
grid_tile_height <- 50/grid_dim
play_by_play_with_free_throw_results_reg_season_attempts %>% data_grid(x = seq(0,50,grid_tile_width), y = seq(0,(94/2),grid_tile_height)) -> grid
grid$true_points <- predict(shot_position_model_gam, grid)
grid %>% filter(true_points >= 0) -> grid
grid %>% pull(true_points) %>% min() -> min_true_shot_value
grid %>% pull(true_points) %>% max() -> max_true_shot_value



#pdf("visuals/true_point_shot_charts.pdf")



play_by_play_with_free_throw_results_reg_season %>% pull(player_shooting_team) %>% unique() -> teams
play_by_play_with_free_throw_results_reg_season %>% pull(season) %>% unique() -> seasons


create_gam_shot_chart(grid,"true_points",paste0("NBA ", min(seasons),"-",min(seasons)-1999, " through ",  max(seasons),"-",max(seasons)-1999, " Seasons"),"GAM True Shot Model","Expected Points",min_true_shot_value, average_true_shot_value, max_true_shot_value) -> gam_shot_chart
#print(gam_shot_chart)
saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/true_nba.png"))


shot_position_model_gam = gam(points ~ s(x,y) ,data=play_by_play_with_free_throw_results_reg_season_attempts %>% filter(is.na(s_foul),simulated_fouled_shot == 0))
grid$points <- predict(shot_position_model_gam, grid)
play_by_play_with_free_throw_results_reg_season_attempts %>% filter(is.na(s_foul),simulated_fouled_shot == 0) %>% pull(points) %>% mean() -> average_fga_shot_value
grid %>% pull(points) %>% min() -> min_true_shot_value
grid %>% pull(points) %>% max() -> max_true_shot_value
create_gam_shot_chart(grid,"points",paste0("NBA ", min(seasons),"-",min(seasons)-1999, " through ",  max(seasons),"-",max(seasons)-1999, " Seasons"),"FGA Expected Points","Expected Points",min_true_shot_value, average_fga_shot_value, max_true_shot_value ) -> gam_shot_chart
  #print(gam_shot_chart)
saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/fga_expected_points_nba.png"))
  
team_shot_selection_data <- tibble()
for (season in seasons){
  current_season <- season
  print(season)
  play_by_play_with_free_throw_results_reg_season_attempts %>% filter(season == current_season) -> data
  data %>% pull(true_points) %>% mean() -> average_true_shot_value
  league_shot_position_model_gam = gam(true_points ~ s(x,y) ,data=data, weights = simulated_fouled_missed_fouled_shots_weight)
  grid_dim <- 200
  grid_tile_width <- 50/grid_dim
  grid_tile_height <- 50/grid_dim
  data %>% data_grid(x = seq(0,50,grid_tile_width), y = seq(0,(94/2),grid_tile_height)) -> grid
  grid$true_points <- predict(league_shot_position_model_gam, grid)
  grid %>% filter(true_points >= 0) -> grid
  grid %>% pull(true_points) %>% min() -> min_true_shot_value
  grid %>% pull(true_points) %>% max() -> max_true_shot_value
  create_gam_shot_chart(grid,"true_points",paste0("NBA ", season,"-",season-1999, " Season"),"GAM True Shot Model","Expected Points",min_true_shot_value, average_true_shot_value, max_true_shot_value ) -> league_gam_shot_chart
  #print(league_gam_shot_chart)
  saveImage(league_gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"-",season-1999, "_Season.png"))
  saveImage(league_gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"-",season-1999, "_Season.svg"))
  
  
  
  shot_position_model_gam = gam(points ~ s(x,y) ,data=data %>% filter(is.na(s_foul),simulated_fouled_shot == 0))
  grid$points <- predict(shot_position_model_gam, grid)
  data %>% filter(is.na(s_foul),simulated_fouled_shot == 0) %>% pull(points) %>% mean() -> average_fga_shot_value
  grid %>% pull(points) %>% min() -> min_true_shot_value
  grid %>% pull(points) %>% max() -> max_true_shot_value
  create_gam_shot_chart(grid,"points",paste0("NBA ", season,"-",season-1999, " Season"),"FGA Expected Points","Expected Points",min_true_shot_value, average_fga_shot_value, max_true_shot_value ) -> gam_shot_chart
    #print(gam_shot_chart)
  saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/fga_expected_points_",season,"-",season-1999, "_Season.png"))
  
  density_estimation <- kde2d(data$x, data$y, n = c((50/grid_tile_width)+1,((94/2)/grid_tile_height)+1), lims = c(0, 50, 0, (94/2)), h=5)
  density_estimation <- vmat2df(density_estimation) %>% rename(density=z)
  grid %>% inner_join(density_estimation, by = c("x", "y")) -> grid
  grid$shot_selection_efficiency <- grid$true_points * grid$density
  grid -> grid_season
  grid_season %>% pull(shot_selection_efficiency) %>% mean() -> average_shot_selection_efficiency
  
  x <- foreach(team = teams, .combine = 'c') %dopar% {
    current_team <- team
    play_by_play_with_free_throw_results_reg_season_attempts %>% filter((season == current_season) & (player_shooting_team==current_team)) -> data
    shot_position_model_gam = gam(true_points ~ s(x,y) ,data=data, weights = simulated_fouled_missed_fouled_shots_weight)
    grid_dim <- 200
    grid_tile_width <- 50/grid_dim
    grid_tile_height <- 50/grid_dim
    data %>% data_grid(x = seq(0,50,grid_tile_width), y = seq(0,(94/2),grid_tile_height)) -> grid
    grid$true_points <- predict(shot_position_model_gam, grid)
    grid$league_true_points <- predict(league_shot_position_model_gam, grid)
    grid$true_points_over_league_average = grid$true_points - grid$league_true_points
    grid %>% filter(true_points >= 0) -> grid

    
    #density_estimation <- kde2d(data$x, data$y, n = c((50/grid_tile_width)+1,((94/2)/grid_tile_height)+1), lims = c(0, 50, 0, (94/2)))
    density_estimation <- kde2d(data$x, data$y, n = c((50/grid_tile_width)+1,((94/2)/grid_tile_height)+1), lims = c(0, 50, 0, (94/2)), h=5)
    density_estimation <- vmat2df(density_estimation) %>% rename(density=z)

    grid %>% inner_join(density_estimation, by = c("x", "y")) -> grid
    grid$shot_selection_efficiency <- grid$true_points * grid$density
    grid %>% inner_join(grid_season, by = c("x", "y"),suffix = c("","_league")) -> grid
 
    
    
    
    grid$density_over_league = grid$density - grid$density_league
    grid$shot_selection_efficiency_over_league = grid$shot_selection_efficiency - grid$shot_selection_efficiency_league
    print(team)
    print(grid %>% head(1))
    grid %>% pull(true_points) %>% min() -> min_true_shot_value
    grid %>% pull(true_points) %>% max() -> max_true_shot_value
    create_gam_shot_chart(grid,"true_points",paste0(team, " ", season,"-",season-1999, " Season"),"GAM True Shot Model","Expected Points" ,min_true_shot_value, average_true_shot_value, max_true_shot_value) -> gam_shot_chart
    #print(gam_shot_chart)
    saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/true_",team, " ", season,"-",season-1999, "_Season.png"))
    
    
    create_gam_shot_chart_two_color(grid,"density",paste0(team, " ", season,"-",season-1999, " Season"),"2D Kernel Density Distribution","Density" ) -> kde_shot_chart
    create_gam_shot_chart(grid,"density_over_league",paste0(team, " ", season,"-",season-1999, " Season"),"2D Kernel Density Distribution of Shots Compared to the League","Density Over League" ,grid %>% pull(density_over_league) %>% min(), 0, grid %>% pull(density_over_league) %>% max()) -> kde_over_league
    saveImage(kde_over_league, filename = paste0("visuals/shot_charts/",season,"/density_over_league_",team, " ", season,"-",season-1999, "_Season.png"))
    
    shot_selection_efficiency_coefficient <- cor(grid$true_points, grid$density)
    
    shot_selection_efficiency_weighted_coefficient <- weightedCorr(x=grid$true_points,y= grid$density,weights= grid$density, method="Pearson")
    
    
    create_gam_shot_chart(grid,"shot_selection_efficiency_over_league",paste0(team, " ", season,"-",season-1999, " Season"),paste0("Shot Selection Efficiency Coefficient: ",round(shot_selection_efficiency_weighted_coefficient,2),".") ,"Efficiency over League",grid %>% pull(shot_selection_efficiency_over_league) %>% min(), 0, grid %>% pull(shot_selection_efficiency_over_league) %>% max()) -> shot_selection_efficiency_over_league
    
    saveImage(shot_selection_efficiency_over_league, filename = paste0("visuals/shot_charts/",season,"/shot_selection_efficiency_over_league_",team, " ", season,"-",season-1999, "_Season.png"))
    
    create_gam_shot_chart_two_color(grid,"shot_selection_efficiency",paste0(team, " ", season,"-",season-1999, " Season"),"Shot Selection Efficiency","Efficiency") -> shot_selection_efficiency
    
    
    grid %>% pull(true_points_over_league_average) %>% min() -> min_true_shot_value
    grid %>% pull(true_points_over_league_average) %>% max() -> max_true_shot_value
    create_gam_shot_chart(grid,"true_points_over_league_average",paste0(team, " ", season,"-",season-1999, " Season"),"GAM True Shot over League Model","Expected Points over League",min_true_shot_value, 0, max_true_shot_value ) -> gam_shot_chart
    #print(gam_shot_chart)
    saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/true_over_league_",team, " ", season,"-",season-1999, "_Season.png"))
    
    saveRDS(grid, file=paste0("rawData/grid_", season, "_", current_team, ".rds"))
    
    shot_position_model_gam = gam(points ~ s(x,y) ,data=data %>% filter(is.na(s_foul),simulated_fouled_shot == 0))
    grid$points <- predict(shot_position_model_gam, grid)
    grid %>% pull(points) %>% min() -> min_true_shot_value
    grid %>% pull(points) %>% max() -> max_true_shot_value
    create_gam_shot_chart(grid,"points",paste0(team, " ", season,"-",season-1999, " Season"),"FGA Expected Points","Expected Points",min_true_shot_value, average_fga_shot_value, max_true_shot_value ) -> gam_shot_chart
    #print(gam_shot_chart)
    saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/fga_expected_points_",team, " ", season,"-",season-1999, "_Season.png"))
    
    team_shot_selection_data %>% bind_rows(tibble(season = season, team = team, shot_selection_efficiency_coefficient = shot_selection_efficiency_coefficient,shot_selection_efficiency_weighted_coefficient=shot_selection_efficiency_weighted_coefficient)) -> team_shot_selection_data
    tibble(season = season, team = team, shot_selection_efficiency_coefficient = shot_selection_efficiency_coefficient,shot_selection_efficiency_weighted_coefficient=shot_selection_efficiency_weighted_coefficient) %>% write_csv(paste0("data/team_data/",team,season,".csv"))
    
    players <- data %>% pull(player_shooting) %>% unique()
    for(player in players){
        play_by_play_with_free_throw_results_reg_season_attempts %>% filter((season == current_season) & (player_shooting_team==current_team) * (player_shooting == player)) -> data
        shot_position_model_gam = gam(true_points ~ s(x,y) ,data=data, weights = simulated_fouled_missed_fouled_shots_weight)
        grid_dim <- 200
        grid_tile_width <- 50/grid_dim
        grid_tile_height <- 50/grid_dim
        data %>% data_grid(x = seq(0,50,grid_tile_width), y = seq(0,(94/2),grid_tile_height)) -> grid
        grid$true_points <- predict(shot_position_model_gam, grid)
        grid$league_true_points <- predict(league_shot_position_model_gam, grid)
        grid$true_points_over_league_average = grid$true_points - grid$league_true_points
        grid %>% filter(true_points >= 0) -> grid
    
        
        #density_estimation <- kde2d(data$x, data$y, n = c((50/grid_tile_width)+1,((94/2)/grid_tile_height)+1), lims = c(0, 50, 0, (94/2)))
        density_estimation <- kde2d(data$x, data$y, n = c((50/grid_tile_width)+1,((94/2)/grid_tile_height)+1), lims = c(0, 50, 0, (94/2)), h=5)
        density_estimation <- vmat2df(density_estimation) %>% rename(density=z)
    
        grid %>% inner_join(density_estimation, by = c("x", "y")) -> grid
        grid$shot_selection_efficiency <- grid$true_points * grid$density
        grid %>% inner_join(grid_season, by = c("x", "y"),suffix = c("","_league")) -> grid
     
        
        
        
        grid$density_over_league = grid$density - grid$density_league
        grid$shot_selection_efficiency_over_league = grid$shot_selection_efficiency - grid$shot_selection_efficiency_league
        print(team)
        print(grid %>% head(1))
        grid %>% pull(true_points) %>% min() -> min_true_shot_value
        grid %>% pull(true_points) %>% max() -> max_true_shot_value
        create_gam_shot_chart(grid,"true_points",paste0(player, " ", team, " ", season,"-",season-1999, " Season"),"GAM True Shot Model","Expected Points" ,min_true_shot_value, average_true_shot_value, max_true_shot_value) -> gam_shot_chart
        #print(gam_shot_chart)
        saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/true_",team, " ", season,"-",season-1999, "_", player, "_Season.png"))
        
        shot_position_model_gam = gam(points ~ s(x,y) ,data=data %>% filter(is.na(s_foul),simulated_fouled_shot == 0))
        grid$points <- predict(shot_position_model_gam, grid)
        grid %>% pull(points) %>% min() -> min_true_shot_value
        grid %>% pull(points) %>% max() -> max_true_shot_value
        create_gam_shot_chart(grid,"points",paste0(player, " ", team, " ", season,"-",season-1999, " Season"),"FGA Expected Points","Expected Points",min_true_shot_value, average_fga_shot_value, max_true_shot_value ) -> gam_shot_chart
        #print(gam_shot_chart)
        saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/fga_expected_points_",team, " ", season,"-",season-1999, "_", player, "_Season.png"))
    }
    
    
    data
    #saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/true_",team, " ", season,"-",season-1999, "_Season.svg"))
  }
}
team_shot_selection_data %>% write_csv("data/gam_team_shot_selection_data.csv")
#dev.off()
```




```{r}
play_by_play_with_free_throw_results_shots  %>% filter(playoffs == F) %>% mutate(true_points_over_expected = true_points-points)->  play_by_play_with_free_throw_results_reg_season
play_by_play_with_free_throw_results_reg_season %>% filter(!is.na(x), !is.na(y), !is.na(true_points_over_expected)) -> play_by_play_with_free_throw_results_reg_season_attempts
play_by_play_with_free_throw_results_reg_season_attempts %>% pull(true_points_over_expected) %>% mean() -> average_true_shot_value
shot_position_model_gam = gam(true_points_over_expected ~ s(x,y) ,data=play_by_play_with_free_throw_results_reg_season_attempts, weights = simulated_fouled_missed_fouled_shots_weight)
grid_dim <- 200
grid_tile_width <- 50/grid_dim
grid_tile_height <- 50/grid_dim
play_by_play_with_free_throw_results_reg_season_attempts %>% data_grid(x = seq(0,50,grid_tile_width), y = seq(0,(94/2),grid_tile_height)) -> grid
grid$true_points_over_expected <- predict(shot_position_model_gam, grid)
grid %>% filter(true_points_over_expected >= 0) -> grid
grid %>% pull(true_points_over_expected) %>% min() -> min_true_shot_value
grid %>% pull(true_points_over_expected) %>% max() -> max_true_shot_value



#pdf("visuals/true_point_over_expected_shot_charts.pdf")



play_by_play_with_free_throw_results_reg_season %>% pull(player_shooting_team) %>% unique() -> teams
play_by_play_with_free_throw_results_reg_season %>% pull(season) %>% unique() -> seasons


create_gam_shot_chart(grid,"true_points_over_expected", paste0("NBA ", min(seasons),"-",min(seasons)-1999, " through ",  max(seasons),"-",max(seasons)-1999, " Seasons"),"GAM True Points over Expected Points Model","True over Expected" ,min_true_shot_value, average_true_shot_value, max_true_shot_value) -> gam_shot_chart
#print(gam_shot_chart)
saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/true_over_expected_nba.png"))
for (season in seasons){
  current_season <- season
  print(season)
  play_by_play_with_free_throw_results_reg_season_attempts %>% filter(season == current_season) -> data
  data %>% pull(true_points_over_expected) %>% mean() -> average_true_shot_value
  league_shot_position_model_gam = gam(true_points_over_expected ~ s(x,y) ,data=data, weights = simulated_fouled_missed_fouled_shots_weight)
  grid_dim <- 200
  grid_tile_width <- 50/grid_dim
  grid_tile_height <- 50/grid_dim
  data %>% data_grid(x = seq(0,50,grid_tile_width), y = seq(0,(94/2),grid_tile_height)) -> grid
  grid$true_points_over_expected <- predict(league_shot_position_model_gam, grid)
  grid %>% filter(is.numeric(true_points_over_expected )) -> grid
  grid %>% pull(true_points_over_expected) %>% min() -> min_true_shot_value
  grid %>% pull(true_points_over_expected) %>% max() -> max_true_shot_value
  create_gam_shot_chart(grid,"true_points_over_expected",paste0("NBA ", season,"-",season-1999, " Season"), "GAM True Net of Expected Points Model","True Net of Expected Points" ,min_true_shot_value, 0, max_true_shot_value)  -> league_gam_shot_chart
  #create_gam_shot_chart(grid,"true_points_over_expected",paste0("NBA ", season,"-",season-1999, " Season"), "GAM True Points over Expected Points Model","True over Expected" ,min_true_shot_value, average_true_shot_value, max_true_shot_value)  -> league_gam_shot_chart
  #print(league_gam_shot_chart)
  saveImage(league_gam_shot_chart, filename = paste0("visuals/shot_charts/true_over_expected_",season,"-",season-1999, "_Season.png"))
  saveImage(league_gam_shot_chart, filename = paste0("visuals/shot_charts/true_over_expected_",season,"-",season-1999, "_Season.svg"))
  
  
  x <- foreach(team = teams, .combine = 'c') %dopar% {
    current_team <- team
    play_by_play_with_free_throw_results_reg_season_attempts %>% filter((season == current_season) & (player_shooting_team==current_team)) -> data
    shot_position_model_gam = gam(true_points_over_expected ~ s(x,y) ,data=data, weights = simulated_fouled_missed_fouled_shots_weight)
    grid_dim <- 200
    grid_tile_width <- 50/grid_dim
    grid_tile_height <- 50/grid_dim
    data %>% data_grid(x = seq(0,50,grid_tile_width), y = seq(0,(94/2),grid_tile_height)) -> grid
    grid$true_points_over_expected <- predict(shot_position_model_gam, grid)
    grid %>% filter(is.numeric(true_points_over_expected)) -> grid
    grid %>% pull(true_points_over_expected) %>% min() -> min_true_shot_values
    grid %>% pull(true_points_over_expected) %>% max() -> max_true_shot_value
    
    create_gam_shot_chart(grid,"true_points_over_expected",paste0(team," ", season,"-",season-1999, " Season"), "GAM True Net of Expected Points Model","True Net of Expected Points" ,min_true_shot_value, 0, max_true_shot_value) -> gam_shot_chart
    #create_gam_shot_chart(grid,"true_points_over_expected",paste0(team," ", season,"-",season-1999, " Season"), "GAM True Points over Expected Points Model","True over Expected" ,min_true_shot_value, average_true_shot_value, max_true_shot_value) -> gam_shot_chart
    #print(gam_shot_chart)
    saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/true_over_expected_",team, " ", season,"-",season-1999, "_Season.png"))
    #saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/true_over_expected_",team, " ", season,"-",season-1999, "_Season.svg"))
    
    players <- data %>% pull(player_shooting) %>% unique()
    for(player in players){
        play_by_play_with_free_throw_results_reg_season_attempts %>% filter((season == current_season) & (player_shooting_team==current_team) * (player_shooting == player)) -> data
        

        shot_position_model_gam = gam(true_points_over_expected ~ s(x,y) ,data=data, weights = simulated_fouled_missed_fouled_shots_weight)
        grid_dim <- 200
        grid_tile_width <- 50/grid_dim
        grid_tile_height <- 50/grid_dim
        data %>% data_grid(x = seq(0,50,grid_tile_width), y = seq(0,(94/2),grid_tile_height)) -> grid
        grid$true_points_over_expected <- predict(shot_position_model_gam, grid)
        grid %>% filter(is.numeric(true_points_over_expected)) -> grid
        grid %>% pull(true_points_over_expected) %>% min() -> min_true_shot_value
        grid %>% pull(true_points_over_expected) %>% max() -> max_true_shot_value
        
        create_gam_shot_chart(grid,"true_points_over_expected",paste0(player, " ", team, " ", season,"-",season-1999, " Season"), "GAM True Net of Expected Points Model","True Net of Expected Points" ,min_true_shot_value, 0, max_true_shot_value) -> gam_shot_chart

        #print(gam_shot_chart)
        saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/true_over_expected_",team, " ", season,"-",season-1999, "_", player, "_Season.png"))
    }
 
    data
  }
  
}

#dev.off()
```
```{r}
play_by_play_with_free_throw_results_reg_season_attempts %>% mutate(player_shooting_opponent_team = ifelse(player_shooting_team == team, opponent_team, team)) -> play_by_play_with_free_throw_results_reg_season_attempts


for (season in seasons){
  current_season <- season
  print(season)
  play_by_play_with_free_throw_results_reg_season_attempts %>% filter(season == current_season) -> data
  data %>% pull(true_points) %>% mean() -> average_true_shot_value
  league_shot_position_model_gam = gam(true_points ~ s(x,y) ,data=data, weights = simulated_fouled_missed_fouled_shots_weight)
  
  x <- foreach(team = teams, .combine = 'c') %dopar% {
    current_team <- team
    play_by_play_with_free_throw_results_reg_season_attempts %>% filter((season == current_season) & (player_shooting_opponent_team==current_team)) -> data
    shot_position_model_gam = gam(true_points ~ s(x,y) ,data=data, weights = simulated_fouled_missed_fouled_shots_weight)
    grid_dim <- 200
    grid_tile_width <- 50/grid_dim
    grid_tile_height <- 50/grid_dim
    data %>% data_grid(x = seq(0,50,grid_tile_width), y = seq(0,(94/2),grid_tile_height)) -> grid
    grid$true_points <- predict(shot_position_model_gam, grid)
    grid$league_true_points <- predict(league_shot_position_model_gam, grid)
    grid$true_points_over_league_average = grid$true_points - grid$league_true_points
    grid %>% filter(true_points >= 0) -> grid
    grid %>% pull(true_points) %>% min() -> min_true_shot_value
    grid %>% pull(true_points) %>% max() -> max_true_shot_value
    create_gam_shot_chart(grid,"true_points",paste0(team, " ", season,"-",season-1999, " Season"),"GAM Opponent True Shot Model","Opponent Expected Points" ,min_true_shot_value, average_true_shot_value, max_true_shot_value) -> gam_shot_chart
    #print(gam_shot_chart)
    saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/opponent_true_",team, " ", season,"-",season-1999, "_Season.png"))
    
    
    grid %>% pull(true_points_over_league_average) %>% min() -> min_true_shot_value
    grid %>% pull(true_points_over_league_average) %>% max() -> max_true_shot_value
    create_gam_shot_chart(grid,"true_points_over_league_average",paste0(team, " ", season,"-",season-1999, " Season"),"GAM Opponent True Shot over League Model","Opponent Expected\nPoints over League",min_true_shot_value, 0, max_true_shot_value ) -> gam_shot_chart
    #print(gam_shot_chart)
    saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/opponent_true_over_league_",team, " ", season,"-",season-1999, "_Season.png"))
    
    data
    #saveImage(gam_shot_chart, filename = paste0("visuals/shot_charts/",season,"/true_",team, " ", season,"-",season-1999, "_Season.svg"))
  }
}

#dev.off()
```

